/**
 * Повний набір текстів інтерфейсу, дослівно з sirocco-prototypes/*.html.
 * Групи в ключах: login.*, opening.*, task.*, steps.*, close.*, blocker.*,
 * hub.* — по одному екрану з ТЗ. shared.* — наскрізні елементи (шапка,
 * кнопки нотатки/критичної проблеми, голосовий запис), які повторюються
 * на кількох екранах буквально однаковим текстом.
 *
 * {фігурні дужки} — місце для підстановки значення в коді (ім'я, число,
 * час тощо), не для редагування в адмінці.
 */
export const uiStrings: { key: string; value: string; note?: string }[] = [
  // ---------- shared.* (наскрізні елементи) ----------
  {
    key: 'shared.shift_status_bar',
    value: 'Зміна відкрита · Відповідальний — {name}',
    note: 'Рядок під шапкою на всіх екранах після відкриття зміни. {name} — ім’я відповідального.',
  },
  { key: 'shared.dock_note', value: 'Додати нотатку до процесу' },
  { key: 'shared.dock_critical', value: 'Повідомити про критичну проблему' },
  { key: 'shared.back', value: 'Назад' },
  { key: 'shared.back_link', value: '‹ Назад', note: 'З шевроном — використовується на екранах хабу.' },
  {
    key: 'shared.voice_hint_idle',
    value: 'Натисни і скажи. Так швидше, ніж друкувати',
    note: 'Підказка під мікрофоном до початку запису (відкриття зміни, «що завадило»).',
  },
  { key: 'shared.voice_hint_recording', value: 'Записую. Натисни ще раз, щоб зупинити' },
  { key: 'shared.voice_hint_unavailable', value: 'Мікрофон недоступний — напиши текстом' },
  { key: 'shared.mic_aria_label', value: 'Записати голосом', note: 'Для читачів з екрана (aria-label кнопки мікрофона).' },
  { key: 'shared.text_placeholder_short', value: 'або напиши коротко', note: 'Плейсхолдер текстового поля під мікрофоном.' },
  { key: 'shared.network_online', value: 'Мережа є', note: 'Підказка (title) на індикаторі мережі в шапці.' },
  { key: 'shared.network_offline', value: 'Працюємо офлайн', note: 'Підказка (title) на індикаторі мережі в шапці.' },
  {
    key: 'shared.pending_sync_template',
    value: '{n} дій очікують синхронізації',
    note: 'Підказка (title) на бейджі кількості дій у черзі офлайн-синку.',
  },
  {
    key: 'shared.queued_offline_notice',
    value: 'Збережено. Немає мережі — надішлеться сама, щойно з’явиться.',
    note: 'Показується замість помилки, коли дію прийнято в офлайн-чергу, а не втрачено.',
  },

  // ---------- login.* (01-login.html) ----------
  { key: 'login.title', value: 'Відповідальний за зміну' },
  { key: 'login.role_worker', value: 'Монтажник' },
  { key: 'login.role_foreman', value: 'Бригадир' },
  { key: 'login.role_owner', value: 'Власник' },
  { key: 'login.not_me', value: 'Це не я' },
  { key: 'login.pin_incomplete', value: 'Введи чотири цифри' },
  { key: 'login.pin_wrong', value: 'Код не підходить. Спробуй ще раз' },
  { key: 'login.pin_clear', value: 'Стерти' },
  { key: 'login.pin_submit', value: 'Вхід' },
  { key: 'login.welcome', value: 'Вітаю, {name}', note: '{name} — ім’я відповідального (тільки перше ім’я).' },
  { key: 'login.opening_shift', value: 'Відкриваємо зміну…' },
  { key: 'login.opening_quality', value: 'Переходимо до контролю якості…' },
  { key: 'login.opening_owner', value: 'Переходимо до зведених звітів…' },

  // ---------- opening.* (02-opening.html) ----------
  {
    key: 'opening.responsible_eyebrow',
    value: '{name} · відповідальний',
    note: '{name} — ім’я відповідального за зміну.',
  },
  { key: 'opening.title', value: 'Відкриваємо зміну' },
  {
    key: 'opening.intro',
    value:
      'Сім питань про робоче місце. По одному на екран.<br>Якщо щось не так — тисни «Не можу», зміна не зупиниться.',
    note:
      'У прототипі текст згадує кнопку «Не можу», хоча сама кнопка підписана «Ні» — залишено дослівно, варто звірити з Тарасом перед показом працівникам.',
  },
  { key: 'opening.start_button', value: 'Почати' },
  { key: 'opening.progress_template', value: '{n} з {total}', note: 'Лічильник над смугою прогресу чек-листа відкриття.' },
  { key: 'opening.yes', value: 'Так' },
  { key: 'opening.no', value: 'Ні' },
  { key: 'opening.problem_eyebrow', value: 'Проблема' },
  { key: 'opening.problem_title', value: 'Що саме не так?' },
  { key: 'opening.problem_send', value: 'Відправити і продовжити' },
  { key: 'opening.handover_eyebrow', value: 'Останнє питання' },
  { key: 'opening.handover_question', value: 'Робоче місце після попередньої зміни відповідає?' },
  {
    key: 'opening.handover_note',
    value: 'Робимо систему кращою, щоб проблема не переїхала далі непоміченою.',
  },
  { key: 'opening.handover_yes', value: 'Так, приймаю' },
  { key: 'opening.not_ready_eyebrow', value: 'Дільниця не готова' },
  { key: 'opening.not_ready_title', value: 'Вкажіть причину' },
  { key: 'opening.not_ready_send', value: 'Повідомити про неготовність дільниці' },
  {
    key: 'opening.not_ready_sent_confirmation',
    value: 'Термінове повідомлення про неготовність дільниці відправлено Тарасу й бригадиру',
  },
  { key: 'opening.done_eyebrow', value: 'Зміну відкрито · відповідальний' },
  { key: 'opening.to_tasks', value: 'До задач на сьогодні' },
  {
    key: 'opening.dock_critical_call',
    value: 'Дзвінок відповідальному / бригадиру',
    note: 'У прототипі кнопка критичної проблеми на екрані відкриття веде на дзвінок, а не на повний екран нотатки — уточнити поведінку при збірці екрана.',
  },

  // ---------- task.* (сітка задач на сьогодні) ----------
  { key: 'task.grid_title', value: 'Задачі на сьогодні' },
  { key: 'task.rework_tag', value: '↻ Переробка', note: 'Позначка на картці задачі, якщо це переробка браку.' },
  {
    key: 'task.grid_empty',
    value: 'На сьогодні задач ще немає — зверніться до бригадира.',
    note: 'Показується, якщо на сьогодні в системі не заведено жодної задачі.',
  },
  { key: 'task.progress_label', value: 'Зроблено сьогодні' },
  { key: 'task.done_button', value: 'Виконано' },
  {
    key: 'task.closed_title',
    value: 'Закрито',
    note: 'Коротка карточка-підтвердження, що показується ~1.5с замість картки задачі, коли лічильник досяг цілі, перед тим як задача зникає зі списку.',
  },
  { key: 'task.all_done_title', value: 'Усі задачі на сьогодні зроблено' },
  { key: 'task.all_done_sub', value: 'Час переходити до аркуша дня і закриття зміни' },
  { key: 'task.to_daily_sheet', value: 'До аркуша дня' },
  { key: 'task.progress_of_template', value: 'з {target}', note: 'Другий, дрібніший рядок лічильника картки, напр. "6 з 20".' },
  {
    key: 'task.progress_save_failed',
    value: 'Не вдалося зберегти — перевір з’єднання й спробуй ще раз.',
    note: 'Показується на картці задачі, якщо запис прогресу не дійшов до сервера (оптимістичне оновлення відкочується).',
  },

  // ---------- steps.* (04-steps.html) ----------
  { key: 'steps.important_step_label', value: 'Важливий крок' },
  { key: 'steps.position_template', value: 'Крок {n} з {total}' },
  { key: 'steps.media_placeholder', value: '📷 фото / схема кроку' },
  { key: 'steps.key_point_label', value: 'Ключовий момент' },
  { key: 'steps.why_label', value: 'Чому' },
  { key: 'steps.next_button', value: 'Далі' },
  { key: 'steps.reference_check_label', value: 'Звірка з еталоном' },
  { key: 'steps.quality_control_label', value: 'Контроль якості' },
  { key: 'steps.reference_check_title', value: 'Порівняй з еталонною деталлю' },
  { key: 'steps.reference_yes', value: 'Так, відповідає' },
  { key: 'steps.reference_no', value: 'Ні, не відповідає' },
  {
    key: 'steps.reference_yes_confirmation',
    value: 'Деталь відповідає еталону. Повертаємось на екран задачі — фіксуємо кількість',
  },
  {
    key: 'steps.reference_no_confirmation',
    value: 'Деталь не відповідає — запис причини (голос/текст) і сигнал відповідальному',
  },

  // ---------- close.* (05-close.html) ----------
  { key: 'close.context_task', value: 'Задача', note: 'Позначка контексту коментаря.' },
  { key: 'close.context_step', value: 'Крок', note: 'Позначка контексту коментаря.' },
  { key: 'close.sheet_eyebrow', value: 'Кінець зміни' },
  { key: 'close.sheet_title', value: 'Аркуш дня' },
  { key: 'close.sheet_sub', value: 'Перевір, що зробили, і додай, якщо є що сказати.' },
  { key: 'close.sheet_section_tasks', value: 'Задачі' },
  { key: 'close.sheet_section_comments', value: 'Що сказали за день' },
  {
    key: 'close.sheet_comments_note',
    value: 'Це вже записано протягом дня. Нічого переписувати не треба.',
  },
  { key: 'close.add_voice', value: 'Додати голосом' },
  { key: 'close.add_text', value: 'Додати текстом' },
  { key: 'close.to_closing', value: 'Перейти до закриття зміни' },
  { key: 'close.badge_done', value: 'готово' },
  { key: 'close.badge_partial', value: 'частково' },
  { key: 'close.badge_not_started', value: 'не почато' },
  { key: 'close.qty_template', value: '{done} з {target}' },
  { key: 'close.of_target_template', value: 'з {target}', note: 'Дрібніший рядок поруч із done у списку задач аркуша дня.' },
  { key: 'close.add_send', value: 'Додати', note: 'Кнопка відправки нового коментаря (голос/текст) на аркуші дня.' },
  { key: 'close.checklist_eyebrow', value: 'Останнє перед виходом' },
  { key: 'close.checklist_title', value: 'Закриття зміни' },
  { key: 'close.checklist_sub', value: 'Пройди список. Три пункти потребують фото.' },
  {
    key: 'close.checklist_incomplete_error',
    value: 'Щось не збіглося — перевір, чи всі пункти позначені й фото на місці.',
    note: 'Показується, якщо сервер відхилив закриття (неповний чек-лист), хоча кнопка на клієнті виглядала активною.',
  },
  {
    key: 'close.photo_upload_failed',
    value: 'Не вдалося завантажити фото. Спробуй ще раз.',
    note: 'Показується, якщо запит на завантаження фото (камера) повернув помилку.',
  },
  {
    key: 'close.answer_save_failed',
    value: 'Не вдалося зберегти відповідь. Спробуй ще раз.',
    note: 'Показується, якщо сервер відхилив відповідь пункту чек-листа (не про мережу — це йде в офлайн-чергу самостійно).',
  },
  {
    key: 'close.confirm_needs_network',
    value: 'Немає мережі — закриття зміни потребує з’єднання. Спробуй ще раз, коли з’явиться.',
    note: 'Показується, якщо фінальне закриття зміни не змогло достукатись до сервера (мережа впала саме зараз).',
  },
  { key: 'close.checklist_submit', value: 'Все зроблено, закрити зміну' },
  { key: 'close.photo_present', value: 'фото є' },
  { key: 'close.photo_required', value: 'фото' },
  { key: 'close.confirm_eyebrow', value: 'Підтвердження' },
  { key: 'close.confirm_title', value: 'Закриваєш зміну' },
  {
    key: 'close.confirm_sub',
    value: 'Ти — {name}. Час: {time}.<br>Після цього зміна закриється, аркуш піде в звіт.',
  },
  {
    key: 'close.confirm_note',
    value:
      'Наступна зміна прийме робоче місце за тим, що ти залишив. Незавершені вузли позначені на етапі.',
  },
  { key: 'close.confirm_button', value: 'Підтверджую, зміну закрито' },
  { key: 'close.confirm_back', value: 'Назад до списку' },
  { key: 'close.done_title', value: 'Зміну закрито' },
  { key: 'close.done_sub_template', value: '{time} · дякую за роботу' },

  // ---------- blocker.* (06-blocker.html, «Що завадило?») ----------
  { key: 'blocker.position_template', value: 'Недобір {n} з {total}' },
  { key: 'blocker.title', value: 'Що завадило?' },
  { key: 'blocker.qty_template', value: '{done} з {target}' },
  { key: 'blocker.of_target_template', value: 'з {target}', note: 'Дрібніший рядок поруч із великим числом done, напр. "14 з 20".' },
  { key: 'blocker.miss_template', value: '−{n}', note: '{n} — скільки бракує до цілі.' },
  {
    key: 'blocker.voice_hint_idle',
    value: 'Скажи своїми словами. Це не про провину — ми шукаємо, що в системі полагодити',
  },
  {
    key: 'blocker.carry_note_template',
    value: 'Задача лишиться відкритою, поки не буде зроблено ще {qty}',
    note: 'Оновлено разом зі зміною моделі задач (2026-09-15) — задача більше не копіюється на завтра, той самий запис лишається відкритим.',
  },
  { key: 'blocker.send_button', value: 'Відправити і далі' },
  {
    key: 'blocker.all_sent_confirmation',
    value: 'Причини відправлено. Задачі лишаться відкритими до виконання.\nДалі — закриття зміни.',
  },

  // ---------- hub.* (07-hub.html) ----------
  { key: 'hub.no_tasks', value: 'На сьогодні задач не призначено', note: 'Показується, якщо на дату немає жодної задачі.' },
  { key: 'hub.eyebrow', value: 'Головна зміни' },
  { key: 'hub.title', value: 'Сьогодні' },
  {
    key: 'hub.sub_template',
    value: '{total} задачі на день. {inProgress} ще в роботі.',
    note: 'В прототипі число узгоджене з відмінком вручну («Три задачі... Дві ще...») — при підстановці числа перевірити українську форму множини.',
  },
  { key: 'hub.current_task_label', value: 'Поточна задача' },
  { key: 'hub.current_task_template', value: '{title} · {done} з {target}' },
  { key: 'hub.current_task_meta', value: 'Задача {n} з {total} · залишилось {remaining}' },
  { key: 'hub.continue_button', value: 'Продовжити роботу' },
  { key: 'hub.changes_tile', value: 'Що змінили за вашими сигналами', note: 'Підпис плитки на хабі.' },
  { key: 'hub.close_shift_tile', value: 'Закрити зміну' },
  { key: 'hub.changes_eyebrow', value: 'Ваш голос працює' },
  { key: 'hub.changes_title', value: 'Що змінили за вашими сигналами', note: 'Заголовок сторінки (окремо від підпису плитки).' },
  {
    key: 'hub.changes_sub',
    value: 'Кожне, що ви сказали, ми розбираємо. Ось що вже зробили.',
  },
  { key: 'hub.note_eyebrow', value: 'Нотатка до процесу' },
  { key: 'hub.critical_eyebrow', value: 'Критична проблема' },
  { key: 'hub.note_title', value: 'Що хочеш сказати?' },
  { key: 'hub.critical_title', value: 'Що сталося?' },
  { key: 'hub.note_sub', value: 'Скажи голосом або напиши. Це потрапить у звіт дня.' },
  { key: 'hub.critical_sub', value: 'Це піде терміновим сигналом Тарасу й бригадиру одразу.' },
  { key: 'hub.mic_aria_label', value: 'Записати', note: 'Коротший варіант aria-label саме на екрані нотатки/проблеми.' },
  { key: 'hub.voice_hint_idle', value: 'Натисни і скажи', note: 'Коротший варіант підказки саме на цьому екрані (без другого речення).' },
  { key: 'hub.attach_button', value: '📷 Додати фото або відео' },
  { key: 'hub.attach_done', value: '📷 Медіа додано' },
  { key: 'hub.send_button', value: 'Відправити' },
  { key: 'hub.send_button_critical', value: 'Відправити терміново' },
  {
    key: 'hub.send_confirmation',
    value: 'Відправлено. Запис із контекстом (задача, час, хто) пішов у звіт / сигнал.',
  },
  { key: 'hub.modal_kind_message', value: 'Повідомлення' },
  { key: 'hub.modal_kind_task', value: 'Нова задача на сьогодні' },
  { key: 'hub.modal_from_admin_template', value: '{name} · CEO · щойно' },
  { key: 'hub.modal_from_foreman_template', value: '{name} · бригадир · щойно' },
  { key: 'hub.modal_ack_message', value: 'Прочитано' },
  { key: 'hub.modal_ack_task', value: 'Прийнято' },

  // ---------- quality.* (контроль якості, екран бригадира) ----------
  { key: 'quality.foreman_bar_template', value: 'Контроль якості · Бригадир — {name}' },
  { key: 'quality.list_eyebrow', value: 'Контроль якості' },
  { key: 'quality.list_title', value: 'Перевірки змін' },
  {
    key: 'quality.list_empty',
    value: 'Ще немає жодної зміни з прогресом по задачах.',
  },
  { key: 'quality.tag_current', value: 'Поточна зміна' },
  { key: 'quality.tag_needs_check', value: 'Потребує перевірки' },
  {
    key: 'quality.summary_template',
    value: 'Перевірено {checked} з {total} задач',
    note: '{checked} і {total} — кількість задач, яких торкались за зміну.',
  },
  { key: 'quality.summary_no_progress', value: 'Прогресу по задачах ще немає' },
  { key: 'quality.summary_has_defect', value: '⚠ є брак' },
  { key: 'quality.readonly_note', value: 'Перегляд минулої зміни — редагування недоступне.' },
  { key: 'quality.no_progress', value: 'У цій зміні ще не було прогресу по жодній задачі.' },
  { key: 'quality.rework_tag', value: 'Переробка' },
  { key: 'quality.qty_done_label', value: 'Заявлено монтажником' },
  { key: 'quality.qty_accepted_label', value: 'Прийнято по якості' },
  {
    key: 'quality.defect_template',
    value: 'Брак: {n} шт — створиться задача-переробка',
    note: '{n} — різниця між заявленим і прийнятим.',
  },
  { key: 'quality.comment_label', value: 'Коментар (обов’язково при браку)' },
  { key: 'quality.comment_placeholder', value: 'Що саме не так з деталями' },
  { key: 'quality.submit_send', value: 'Відправити перевірку' },
  { key: 'quality.submit_update', value: 'Оновити перевірку' },
  { key: 'quality.submit_failed', value: 'Не вдалося зберегти. Спробуй ще раз.' },
  {
    key: 'quality.submit_done_title',
    value: 'Перевірку збережено',
    note: 'Заголовок повноекранного підтвердження після відправки/оновлення перевірки.',
  },
  {
    key: 'quality.submit_done_sub',
    value: 'Дані передані в систему',
    note: 'Свідомо НЕ "передано в Slack" — клієнт не знає статус Slack-сповіщення (after() виконується вже після відповіді).',
  },
  { key: 'quality.submit_done_to_list', value: 'До списку перевірок' },
  { key: 'quality.submit_done_check_again', value: 'Ще раз перевірити' },

  // ---------- owner.* (режим власника) ----------
  { key: 'owner.bar_template', value: 'Власник — {name}' },
  { key: 'owner.list_eyebrow', value: 'Зведені звіти' },
  { key: 'owner.list_title', value: 'Зміни' },
  { key: 'owner.list_empty', value: 'Ще немає жодної зміни.' },
  { key: 'owner.badge_checked', value: 'Перевірено бригадиром' },
  { key: 'owner.badge_not_checked', value: 'Ще не перевірено' },
  { key: 'owner.badge_no_tasks', value: 'Без задач' },
  {
    key: 'owner.row_open_template',
    value: 'Відкрито {time}',
    note: '{time} — час відкриття зміни.',
  },
  {
    key: 'owner.row_closed_template',
    value: 'Закрито {time}',
    note: '{time} — час закриття зміни.',
  },
  { key: 'owner.row_still_open', value: 'Ще відкрита' },
  { key: 'owner.row_auto_closed', value: 'Автозакрито' },
  { key: 'owner.field_responsible', value: 'Відповідальний' },
  { key: 'owner.handover_problem', value: 'Були зауваження при прийманні' },
  { key: 'owner.rework_tag', value: 'Переробка' },
  { key: 'owner.section_tasks', value: 'Задачі' },
  { key: 'owner.section_tasks_empty', value: 'Прогресу по задачах не було.' },
  { key: 'owner.section_gaps', value: 'Причини недобору' },
  { key: 'owner.section_gaps_empty', value: 'Недобору не було.' },
  { key: 'owner.section_quality', value: 'Перевірка бригадиром' },
  { key: 'owner.section_quality_empty', value: 'Перевірки ще не було.' },
  { key: 'owner.section_comments', value: 'Коментарі зміни' },
  { key: 'owner.section_comments_empty', value: 'Коментарів не було.' },
  { key: 'owner.section_opening_checklist', value: 'Чек-лист відкриття' },
  { key: 'owner.section_closing_checklist', value: 'Чек-лист закриття' },
  { key: 'owner.checklist_not_completed', value: 'Чек-лист не завершено' },
  { key: 'owner.section_photos', value: 'Фото закриття' },
  { key: 'owner.section_photos_empty', value: 'Фото немає.' },
  { key: 'owner.copy_log_button', value: 'Скопіювати весь лог' },
  { key: 'owner.copy_log_done', value: 'Скопійовано' },

  // ---------- owner.task_* (керування задачами, ЕТАП 3) ----------
  { key: 'owner.tasks_section_eyebrow', value: 'Збиральна дільниця' },
  { key: 'owner.tasks_section_title', value: 'Активні задачі' },
  { key: 'owner.tasks_section_empty', value: 'Активних задач немає.' },
  { key: 'owner.task_completed_badge', value: 'Закрита' },
  { key: 'owner.task_progress_badge', value: 'Є прогрес' },
  { key: 'owner.task_checked_badge', value: 'Перевірена' },
  {
    key: 'owner.task_qty_template',
    value: '{done} з {target}',
    note: '{done} — накопичено за весь час, {target} — поточна ціль (targetQty).',
  },
  { key: 'owner.task_edit_button', value: 'Редагувати' },
  { key: 'owner.task_target_update_failed', value: 'Не вдалося оновити ціль. Спробуй ще раз.' },
  { key: 'owner.task_edit_modal_title', value: 'Редагувати задачу' },
  { key: 'owner.task_title_label', value: 'Назва' },
  { key: 'owner.task_description_label', value: 'Опис' },
  { key: 'owner.task_save_button', value: 'Зберегти' },
  { key: 'owner.task_cancel_button', value: 'Скасувати' },
  { key: 'owner.task_save_failed', value: 'Не вдалося зберегти. Спробуй ще раз.' },
  { key: 'owner.task_create_button', value: 'Нова задача' },
  { key: 'owner.task_create_modal_title', value: 'Нова задача' },
  { key: 'owner.task_target_qty_label', value: 'Ціль, шт' },
  { key: 'owner.task_create_submit', value: 'Створити' },
  { key: 'owner.task_create_failed', value: 'Не вдалося створити. Спробуй ще раз.' },
]
